### ISSUE TITLE
Support for cachecontrol >=0.13.1

### ISSUE THREAD

**Issue by NickBoyett** [Bandwidth/python-sdk#162]
Hoping to resolve the following

`bandwidth-sdk 14.5.2 has requirement cachecontrol~=0.12.6, but you have cachecontrol 0.13.1.`

**Comment by ajrice6713** [comment]
Hey Nick! 

Are you already onboarded/integrated with this SDK? Or are you just starting? We have a beta out that should satisfy your requirements, but there are lots of breaking changes. 

I can get these bumped if its a requirement for ya to use the current version (14) of the SDK. Otherwise i recommend checking out the beta as that is the version we will support going forward! The current beta is `v15.0.0b2`

**Comment by ajrice6713** [comment]
Hey @NickBoyett - just wanted to follow up and see if you saw my previous comment

**Comment by ajrice6713** [comment]
Hey @NickBoyett - ill get these dependencies updated for v14, the v15 beta should be out on 10/24 and we have some migration guides that can be found [here](https://dev.bandwidth.com/migration-guides/python/v14-%3Ev15-beta). Let me know if you have any questions!

**Comment by ajrice6713** [comment]
Hey @NickBoyett - sorry for the delay, this fix was released last week in 14.5.3! Ill close this out, but feel free to reopen if you have any problems!
